apiVersion: apps/v1
kind: Deployment
metadata:
  name: dghcnk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dghcnk
  template:
    metadata:
      labels:
        app: dghcnk
    spec:
      containers:
      - image: okteto.dev/dghcnk:latest
        name: dghcnk
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "f1a2e98d-81bc-4b25-8662-9d28f145bf5a"
        - name: Vless_Path
          value: "/f1a2e98d-81bc-4b25-8662-9d28f145bf5a"
        - name: Vmess_UUID
          value: "67756e6e-7a77-4750-b534-1723c7a80b6d"
        - name: Vmess_Path
          value: "/67756e6e-7a77-4750-b534-1723c7a80b6d"
        - name: Share_Path
          value: "/v2link"
